### ISSUE TITLE
🐛 Bug Report: npm dependencies resolution issue

### ISSUE THREAD

**Issue by gaelgoth** [procore-oss/backstage-plugin-announcements#235]
### 📜 Description

I don't know much about publishing package to npm, but `yarn` can't link correct version of the plugin. 

Our Renovate bot that updates our dependencies tried to upgrade `@procore-oss/backstage-plugin-...` but cannot link dependency with the correct latest version but uses `@workspace:^` local version.

### 👍 Expected behavior

For example, `yarn add --cwd packages/backend @procore-oss/backstage-plugin-search-backend-module-announcements` should automatically resolve current version  `0.1.1`

### 👎 Actual Behavior with Screenshots

It actually lead to this error and can found local workspace plugin:

 ```
YN0001: │ Error: @procore-oss/backstage-plugin-announcements-common@workspace:^: Workspace not found (@procore-oss/backstage-plugin-announcements-common@workspace:^)
```

It should npm version: 

```
"@procore-oss/backstage-plugin-announcements-common": "npm:^0.1.4"
```

### 👟 Reproduction steps

- I did a fresh install of Backstage:  `npx @backstage/create-app@latest`
- Then install backend plugin:
```shell
$ yarn add --cwd packages/backend @procore-oss/backstage-plugin-announcements-backend
yarn add v1.22.19
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "@types/react@^16.13.1 || ^17.0.0". Ignoring it.
Couldn't find any versions for "@procore-oss/backstage-plugin-announcements-common" that matches "workspace:^"
? Please choose a version of "@procore-oss/backstage-plugin-announcements-common" from this list: (Use arrow keys)
❯ 0.1.4
  0.1.3
  0.1.2
  0.1.1
Couldn't find any versions for "@procore-oss/backstage-plugin-search-backend-module-announcements" that matches "workspace:^"
? Please choose a version of "@procore-oss/backstage-plugin-search-backend-module-announcements" from this list: (Use ar
row keys)
❯ 0.1.1
  0.1.0
```
- Then yarn prompts that it can't find `"workspace:^"` version.

### 📃 Provide the context for the Bug.

Our main instance use yarn v4 and I reproduced it with yarn v1.22, got similar results on both version

### 🖥️ Your Environment

```
yarn run v1.22.19
$ /home/ggt/gaelgoth-github/tests/debug-package-resolution/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.133.1-microsoft-standard-WSL2 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.1

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by wss-alubic** [comment]
Try these steps:

1. `yarn cache clean`
2. `rm yarn.lock`
3. `yarn install` - you may be asked to choose a version on several packages, just pick latest.

This resolved the issue for me and now I'm able to update to latest.

**Comment by kurtaking** [comment]
@gaelgoth, let me know if @wss-alubic instructions work, and we will go from there.

**Comment by codingdiaz** [comment]
@kurtaking I'm running into this same issue. I tried the above steps and that didn't work. I'm running node version `v20.22.0` and yarn version `4.0.2`.

**Comment by kurtaking** [comment]
@codingdiaz thanks for sharing. Tuesdays are my busiest nights of the week. 
I won't have time to look at this until tomorrow.

**Comment by gaelgoth** [comment]
I confirm that running `yarn add @procore-oss/backstage-plugin-announcements-backend@0.5.3` works as expected. But it doesn't work with latest version (`0.5.4`): 
```shell
➤ YN0001: │ Error: @procore-oss/backstage-plugin-announcements-common@workspace:^: Workspace not found (@procore-oss/backstage-plugin-announcements-common@workspace:^)
    at Pt.getWorkspaceByDescriptor (/home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:210:3520)
    at l1.getCandidates (/home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:140:115276)
    at Dd.getCandidates (/home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:141:1311)
    at Dd.getCandidates (/home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:141:1311)
    at /home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:210:8409
    at Ky (/home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:140:53916)
    at Fe (/home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:210:8389)
    at async Promise.allSettled (index 10)
    at async Uc (/home/user/workspace/backstage/.yarn/releases/yarn-4.1.0.cjs:140:53244)
➤ YN0000: └ Completed in 0s 812ms
➤ YN0000: · Failed with errors in 0s 821ms
```
I think it is related on these changes on package. Maybe some adaptations need to be done to tell changeset to set version for published release ?: 
https://github.com/procore-oss/backstage-plugin-announcements/commit/f7b3b0b92bc3b5356f50fb0111f482526c716ce7#diff-12939dbee1121abad884fb2d88194561bda99b5d2ad39b5756d2fb7379bfdee5

**Comment by kurtaking** [comment]
Hmm, yeah, I don't understand things well enough. I plan to look at how backstage is doing this later today.

**Comment by kurtaking** [comment]
Still here, still stumped 😞

**Comment by vinzscam** [comment]
I think the issue is related to the script you are running for releasing the plugins.
Your release script is `changeset publish` https://github.com/procore-oss/backstage-plugin-announcements/blob/main/package.json#L23
which under the hood it invokes `npm publish` (which might have troubles resolving the linked packages) instead of `yarn npm publish`.

**Comment by kurtaking** [comment]
> I think the issue is related to the script you are running for releasing the plugins. Your release script is `changeset publish` https://github.com/procore-oss/backstage-plugin-announcements/blob/main/package.json#L23 which under the hood it invokes `npm publish` (which might have troubles resolving the linked packages) instead of `yarn npm publish`.

Hey @vinzscam, thanks for taking a look! This gives me some direction to explore.

**Comment by kurtaking** [comment]
I published new patch versions of all packages using different commands based on @vinzscam recommendation and [this issue](https://github.com/changesets/changesets/issues/432#issuecomment-1258264936).

@gaelgoth, @codingdiaz - can either of you report back on updating to the latest patch versions?

**Comment by gaelgoth** [comment]
Well done, I was able to update the plugin to the latest version: 

```json
 "@procore-oss/backstage-plugin-announcements-backend": "^0.5.5",
 "@procore-oss/backstage-plugin-announcements-common": "^0.1.5",
```

Thank your for the fix

**Comment by codingdiaz** [comment]
@kurtaking, thanks a ton! I'm able to update to the latest versions.
